### ISSUE TITLE
Running Qlik CLI commands from Windows Scheduler not working

### ISSUE THREAD

**Issue by rkumar1609** [ahaydon/Qlik-Cli#93] opened 2019-10-01 19:23 UTC
Hi Techies,

I got a use case where I need to trigger a Qlik Sense task right after Windows Task Scheduler task completion.

I have installed and configured Qlik CLI module in powershell. I have created one .ps1 file which has two commands:

Get-ChildItem cert:CurrentUser\My | Where-Object { $_.FriendlyName -eq 'QlikClient' } | Connect-Qlik sense-central; Start-QlikTask "Manually triggered reload of Task" -wait | Wait-QlikExecution

Decoding abvove command in ps1 file:  Connecting certificates Get-ChildItem cert:CurrentUser\My | Where-Object { $_.FriendlyName -eq 'QlikClient' }  

Trigger Qlik Sense task : Connect-Qlik sense-central; Start-QlikTask "Manually triggered reload of Task" -wait | Wait-QlikExecution

When I am running this .ps1 file in powershell it is triggering Qlik task successful but I have a use case where I need to run the above powershell command in windows task scheduler.

Above command I found on page https://github.com/ahaydon/Qlik-Cli

In simple I need to run Qlik Cli command by Windows Task Scheduler.  

I tried few stack over flow solution like https://stackoverflow.com/questions/13015245/powershell-script-wont-execute-as-a-windows-scheduled-t...

but it is not working. 0*1 is the message coming out. Running directly .ps1 file works fine.

Can you please help me to run a Qlik CLI command through Windows Task Scheduler ?

 

Thanks,

Rohit

**Comment by clintcarr** [comment] 2019-10-18 00:15
What user are you running the scheduled task as?,  it may not find the certificate in the CurrentUser if the user doesnt have that cert in CurrentUser.

**Comment by Nillth** [comment] 2019-11-21 01:56
the friendlyname should be CN=QlikClient e.g.

`Get-ChildItem cert:CurrentUser\My | Where-Object { $_.FriendlyName -eq 'CN=QlikClient' } |Connect-Qlik sense-central; Start-QlikTask "Manually triggered reload of Task" -wait | Wait-QlikExecution
`

**Comment by vbakke** [comment] 2019-12-11 12:21
@rkumar1609 , have you got this running? 

What do you get if you run: 
`Get-ChildItem cert:CurrentUser\My | Where-Object { $_.FriendlyName -eq 'CN=QlikClient' }`
all by it self?

What do you get if you run: 
`Get-ChildItem cert:CurrentUser\My | Where-Object { $_.FriendlyName -eq 'CN=QlikClient' } >> c:\file.txt`
in the scheduled task?

If you don't get anything, the problem is that the certificate is missing.

If that is the case, I suggest that we close this issue.  (The only improvement, I see, is clarifying the documentation. : )

**Comment by Nillth** [comment] 2020-03-30 01:58
Stale

**Closed by Nillth** 2020-03-30 01:58 UTC
