### ISSUE TITLE
Assign user customproperties based on csv file

### ISSUE THREAD

**Issue by aarongiesinger** [ahaydon/Qlik-Cli#220] opened 2024-05-14 06:46 UTC
Hy,
I'm trying to create a script which replace assigned Customproperty Values to a User by Values out of a csv File.

My Code:
$CSVUsers = Get-Content D:\XXXXXX\XXXXX.csv|ConvertFrom-Csv
foreach ($CSVUser in $CSVUsers) 
{
    $QSUser = Get-QlikUser -id $CSVUser.User -raw
    [string[]]$customProperties = ""
    [string[]]$customProperties = $($QSUser.customProperties|%{"$($_.definition.Name)=$($_.value)"})
    $customProperties+=$CSVUser.App
    $QSUser | Update-QlikUser -customProperties $customProperties
}

If i execute it when no CustomProperty Value is assigned to a User it works fine. But when it is executed the second time following error will be displayed:
Invoke-RestMethod : The remote server returned an error: (409) Conflict.
At C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\1.23.1\functions\core.ps1:69 char:23
+ ...            $result = Invoke-RestMethod @paramInvokeRestMethod @params
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Can anyone help me?

Thanks a lot,
BR Aaron

**Comment by ahaydon** [comment] 2024-05-14 09:47
The error is likely caused by attempting to add a property value that is already set for the user, try the following change to only append the value if it's not already set.
```powershell
if ($customProperties -notcontains $CSVUser.App) {
  $customProperties+=$CSVUser.App
}
```

**Comment by aarongiesinger** [comment] 2024-05-14 10:08
Hy ahadon,
Thanks - this will work an remove the error.
But is there a way to overwrite all allocations. I only want to assign the CustomProperties which are in the csv file.

 Thank you in advance,
BR Aaron

**Comment by ahaydon** [comment] 2024-05-14 10:14
If you want to discard all existing values assigned to the user and just set the value from the CSV file then you don't need to get the existing values and combine them with the new value. Just set the new values as in the following example:
```powershell
$CSVUsers = Get-Content D:\XXXXXX\XXXXX.csv|ConvertFrom-Csv
foreach ($CSVUser in $CSVUsers) {
  Update-QlikUser -id $CSVUser.User -customProperties $CSVUser.App
}
```

**Comment by aarongiesinger** [comment] 2024-05-14 10:26
Hy ahaydon,
this will only add the "last" Custom Property of a userid.

My CSV file look like:

UserID,CustomProperty
ef621fb9-512a-41a0-a156-bcb30210e13d,CustomPropName=Value1
ef621fb9-512a-41a0-a156-bcb30210e13d,CustomPropName=Value2
ef621fb9-512a-41a0-a156-bcb30210e13d,CustomPropName=Value3
39ea0fb8-ceb2-4179-a5a0-de35a3d8f4be,CustomPropName=Value2

Do I have to change the CSV data to get it work?
Thanks a lot,
BR Aaron

**Comment by ahaydon** [comment] 2024-05-14 11:07
Each row of the CSV file is processed independently so there's no context to know if the existing values were applied from a previous row or existed before the script run. Each user needs to be processed as a single transaction to set all properties from the CSV that relate to that user, you can do this using the `Group-Object` command. E.g.
```powershell
$CSVUsers = Get-Content D:\XXXXXX\XXXXX.csv | ConvertFrom-Csv | Group-Object -Property UserID
foreach ($CSVUser in $CSVUsers) {
  Update-QlikUser -id $CSVUser.Name -customProperties $CSVUser.Group.CustomProperty
}
```

**Comment by aarongiesinger** [comment] 2024-05-14 11:27
THANK YOU - That's exactly what I want... 
Have a nice day,
 BR Aaron

**Closed as completed** 2024-05-14 11:27 UTC
